# Plant Disease Detection Configuration
dataset_name: "plantvillage"
model_name: "efficientnet_b0"
image_size: 224
batch_size: 32
num_workers: 4
max_epochs: 100
patience: 15

# Training parameters
learning_rate: 0.001
weight_decay: 0.0001
dropout_rate: 0.2

# Augmentation
use_randaugment: true
use_mixup: true
use_cutmix: true
mixup_alpha: 0.2
cutmix_alpha: 1.0

# Loss function
use_focal_loss: false
focal_alpha: 0.25
focal_gamma: 2.0

# Hyperparameter optimization
n_trials: 20

# Logging
use_wandb: true
project_name: "khet-guard-plant-disease"
run_name: "efficientnet_b0_plantvillage"

# Hardware
devices: 1
seed: 42
